version: "3.4"
services:
  node-app:
    build: 
      context: .
      target: development  
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672    
         